stages:
  data_ingestion:
    cmd: python src/project/pipeline/stage_01.py
    deps:
      - src/project/pipeline/stage_01.py
      - src/project/config/config.py
      - src/project/entity/config_entity.py
      - src/project/utils/common.py
      - yaml file/config.yaml
    outs:
      - artifacts/data_ingestion/data.zip
      - artifacts/data_ingestion/Fraud-data.csv

  data_validation:
    cmd: python src/project/pipeline/stage_02.py
    deps:
      - src/project/pipeline/stage_02.py
      - src/project/config/config.py
      - src/project/components/data_validation.py
      - src/project/entity/config_entity.py
      - yaml file/config.yaml
      - yaml file/schema.yaml
      - artifacts/data_ingestion/Fraud-data.csv
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python src/project/pipeline/stage_03.py
    deps:
      - src/project/pipeline/stage_03.py
      - src/project/config/config.py
      - src/project/components/data_transformation.py
      - src/project/entity/config_entity.py
      - src/project/utils/common.py
      - yaml file/config.yaml
      - yaml file/schema.yaml
      - yaml file/params.yaml
      - artifacts/data_ingestion/Fraud-data.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train_processed.npy
      - artifacts/data_transformation/test_processed.npy
      - artifacts/data_transformation/preprocessor.pkl
      - artifacts/data_transformation/label_encoders.pkl

  model_training:
    cmd: python src/project/pipeline/stage_04.py
    deps:
      - src/project/pipeline/stage_04.py
      - src/project/config/config.py
      - src/project/components/model_training.py
      - src/project/entity/config_entity.py
      - src/project/utils/common.py
      - yaml file/config.yaml
      - yaml file/params.yaml
      - yaml file/schema.yaml
      - artifacts/data_transformation/train_processed.npy
      - artifacts/data_transformation/test_processed.npy
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python src/project/pipeline/stage_05.py
    deps:
      - src/project/pipeline/stage_05.py
      - src/project/config/config.py
      - src/project/components/model_evaluation.py
      - src/project/entity/config_entity.py
      - src/project/utils/common.py
      - yaml file/config.yaml
      - yaml file/params.yaml
      - yaml file/schema.yaml
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/preprocessor.pkl
      - artifacts/model_trainer/model.joblib
    outs:
      - artifacts/model_evaluation/metrics.json
      - artifacts/model_evaluation/cm.png
      - artifacts/model_evaluation/roc.png