stages:
  data_ingestion:
    cmd: python -m project.components.modelpipeline DataIngestionPipeline
    deps:
      - project/components/data_ingestion.py
      - project/pipeline/modelpipeline.py
      - project/config/config.py
      - project/entity/config_entity.py
    outs:
      - artifacts/data_ingestion/creditcard.csv.zip
      - artifacts/data_ingestion/unzipped_data/creditcard.csv

  data_validation:
    cmd: python -m project.components.modelpipeline DataValidationPipeline
    deps:
      - project/components/data_validation.py
      - project/pipeline/modelpipeline.py
      - project/config/config.py
      - project/entity/config_entity.py
      - artifacts/data_ingestion/unzipped_data/creditcard.csv
    outs:
      - artifacts/data_validation/status.txt

  data_transformation:
    cmd: python -m src.project.components.modelpipeline DataTransformationPipeline
    deps:
      - project/components/data_transformation.py
      - project/pipeline/modelpipeline.py
      - project/config/config.py
      - project/entity/config_entity.py
      - artifacts/data_ingestion/unzipped_data/creditcard.csv
    outs:
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/train_processed.npy
      - artifacts/data_transformation/test_processed.npy
      - artifacts/data_transformation/preprocessor.pkl
      - artifacts/data_transformation/label_encoders.pkl

  model_training:
    cmd: python -m project.components.modelpipeline ModelTrainingPipeline
    deps:
      - project/components/model_training.py
      - project/pipeline/modelpipeline.py
      - project/config/config.py
      - project/entity/config_entity.py
      - artifacts/data_transformation/train_processed.npy
      - artifacts/data_transformation/test_processed.npy
    outs:
      - artifacts/model_trainer/model.joblib

  model_evaluation:
    cmd: python -m project.components.modelpipeline ModelEvaluationPipeline
    deps:
      - project/components/model_evaluation.py
      - project/pipeline/modelpipeline.py
      - project/config/config.py
      - project/entity/config_entity.py
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/preprocessor.pkl
      - artifacts/model_trainer/model.joblib
    outs:
      - artifacts/model_evaluation/metrics.json
      - artifacts/model_evaluation/cm.png
      - artifacts/model_evaluation/roc.png