artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/JavithNaseem-J/Booking.com_SQL/raw/refs/heads/main/data.zip
  zip_file: artifacts/data_ingestion/data.zip
  unzip_file: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_file: artifacts/data_ingestion/Fraud-data.csv
  status_file: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/Fraud-data.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
  label_encoder: artifacts/data_transformation/label_encoders.pkl
  feature_encoder: artifacts/data_transformation/feature_encoders.pkl


model_trainer:
  root_dir: artifacts/model_trainer
  train_path: artifacts/data_transformation/train.csv 
  test_path: artifacts/data_transformation/test.csv 
  train_preprocess: artifacts/data_transformation/train_processed.npy
  test_preprocess: artifacts/data_transformation/test_processed.npy
  model_name: model.joblib


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_path: artifacts/data_transformation/test.csv
  preprocess_path: artifacts/data_transformation/preprocessor.pkl
  model_path: artifacts/model_trainer/model.joblib 
  metrics_path: artifacts/model_evaluation/metrics.json
  cm_path: artifacts/model_evaluation/cm.png
  roc: artifacts/model_evaluation/roc.png
